name: oshinstar
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  country_code_picker: ^3.0.0
  http: ^1.2.1
  url_launcher: ^6.2.6
  websafe_svg: ^3.0.1+1
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.5
  pin_code_fields: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_sliding_box: ^1.1.5
  dotted_border: ^2.1.0
  material_design_icons_flutter: ^7.0.7296
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/industries/
  
