name: oshinstar
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  country_code_picker: ^3.0.0
  http: ^1.2.1
  url_launcher: ^6.2.6
  websafe_svg: ^3.0.1+1
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.5
  pin_code_fields: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_sliding_box: ^1.1.5
  dotted_border: ^2.1.0
  material_design_icons_flutter: ^7.0.7296
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  hydrated_bloc: ^9.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.4.0
  shared_preferences: ^2.2.3
  local_auth: ^2.2.0
  # user:
  #   path: packages/user

  build_runner: ^2.4.11
  web_socket_channel: ^3.0.0
  pretty_qr_code: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  image_path_android: "assets/oshinstar-logo.png"
  image_path_ios: "assets/Isologo-jpg-1024 1.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/oshinstar-logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/industries/
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic

  
