name: user
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.12.0 <3.0.0'

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  build_runner:
  freezed: 
  isar_generator: ^3.1.0+1
  json_serializable:
  lints:
  test:
dependencies:
  freezed_annotation:
  http:
  isar:
  json_annotation:
